[project]
name = "adsi-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.34",
    "fastapi>=0.115.0",
    "uvicorn>=0.31.0",
]
